languageCode: "en-us"
title: "Artur Dryomov"

baseUrl: "http://arturdryomov.online"
permalinks:
  post: ":slug"

menu:
  left:
    - name: "Posts"
      url: "/"
  right:
    - name: "GitHub"
      url: "https://github.com/ming13"
      weight: 3
    - name: "Twitter"
      url: "https://twitter.com/arturdryomov"
      weight: 2
    - name: "RSS"
      url: "/index.xml"
      weight: 1

theme: "barebones"

googleAnalytics: "UA-123-45"

disableHugoGeneratorInject: true
enableEmoji: true
footnoteReturnLinkContents: "↩"

